src/Entity/Tournament.php
<?php

namespace App\Entity;

use App\Repository\TournamentRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Validator\Constraints as Assert;

#[ORM\Entity(repositoryClass: TournamentRepository::class)]
class Tournament
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column(type: 'integer')]
    private $id;

    #[Assert\NotNull]
    #[Assert\NotBlank]
    #[Assert\Length(max: 50)]
    #[ORM\Column(type: 'string', length: 50)]
    private $name;

    #[Assert\NotNull]
    #[Assert\GreaterThanOrEqual('today')]
    #[ORM\Column(type: 'date')]
    private $date;

    #[Assert\NotBlank]
    #[Assert\Length(max: 100)]
    #[ORM\Column(type: 'string', length: 100, nullable: true)]
    private $location;

    #[Assert\NotNull]
    #[Assert\Range(min: 0, max: 3000)]
    #[ORM\Column(type: 'integer', nullable: true)]
    private $eloMin = 0;

    #[Assert\NotNull]
    #[Assert\Range(min: 0, max: 3000)]
    #[Assert\Expression('value >= this.getEloMin()')]
    #[ORM\Column(type: 'integer', nullable: true)]
    private $eloMax = 0;

    #[Assert\NotNull]
    #[ORM\Column(type: 'boolean')]
    private $ranked = true; // default value

    #[Assert\NotNull]
    #[Assert\Count(min: 1)]
    #[ORM\Column(type: 'json')] // used for array // mapped to enum in getter
    private $categories = []; // default value

    #[Assert\NotNull]
    #[Assert\Count(min: 1)]
    #[ORM\Column(type: 'json')] // used for array
    private $genders = [];

    #[Assert\NotNull]
    #[Assert\Range(min: 2, max: 100)]
    #[ORM\Column(type: 'integer')]
    private $min = 2;

    #[Assert\NotNull]
    #[Assert\Range(min: 2, max: 100)]
    #[Assert\Expression('value >= this.getMin()')]
    #[ORM\Column(type: 'integer')]
    private $max = 2;

    #[ORM\Column(type: 'integer')]
    private $currentRound;

    #[ORM\ManyToMany(targetEntity: Player::class)]
    #[ORM\JoinColumn(onDelete: 'CASCADE')]
    public $players;

    #[ORM\OneToMany(targetEntity: TournamentMatch::class, mappedBy: 'tournament')]
    public $matches;

    public function __construct()
    {
        $this->players = new ArrayCollection();
        $this->matches = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    /**
     * @return string
     */
    public function getName() : string
    {
        return $this->name;
    }

    /**
     * @param string $name
     * @return Tournament
     */
    public function setName(string $name) : Tournament
    {
        $this->name = $name;
        return $this;
    }

    /**
     * @return \DateTime
     */
    public function getDate() : \DateTime
    {
        return $this->date;
    }

    /**
     * @param \DateTime $date
     * @return Tournament
     */
    public function setDate(\DateTime $date) : Tournament
    {
        $this->date = $date;
        return $this;
    }

    /**
     * @return string
     */
    public function getLocation(): string
    {
        return $this->location;
    }

    /**
     * @param string $location
     * @return Tournament
     */
    public function setLocation(string $location) : Tournament
    {
        $this->location = $location;
        return $this;
    }

    /**
     * @return ?int
     */
    public function getEloMin() : ?int
    {
        return $this->eloMin;
    }

    /**
     * @param ?int $eloMin
     * @return Tournament
     */
    public function setEloMin(?int $eloMin) : Tournament
    {
        $this->eloMin = $eloMin;
        return $this;
    }

    /**
     * @return ?int
     */
    public function getEloMax() : ?int
    {
        return $this->eloMax;
    }

    /**
     * @param ?int $eloMax
     * @return Tournament
     */
    public function setEloMax(?int $eloMax) : Tournament
    {
        $this->eloMax = $eloMax;
        return $this;
    }

    /**
     * @return bool
     */
    public function isRanked(): bool
    {
        return $this->ranked;
    }

    /**
     * @param bool $ranked
     * @return Tournament
     */
    public function setRanked(bool $ranked): Tournament
    {
        $this->ranked = $ranked;
        return $this;
    }

    public function getRanked(): ?bool
    {
        return $this->ranked;
    }

    public function getCategories(): array
    {
        return array_map(function($item) {
            return TournamentCategory::from($item);
        }, $this->categories);
    }

    public function setCategories(array $categories): self
    {
        $this->categories = $categories;

        return $this;
    }

    public function getGenders(): array
    {
        return array_map(function($item) {
            return Gender::from($item);
        }, $this->genders);
    }

    public function setGenders(array $genders): self
    {
        $this->genders = $genders;

        return $this;
    }

    /**
     * @return int
     */
    public function getMin() : int
    {
        return $this->min;
    }

    /**
     * @param int $min
     * @return Tournament
     */
    public function setMin(int $min) : self
    {
        $this->min = $min;
        return $this;
    }

    /**
     * @return int
     */
    public function getMax() : int
    {
        return $this->max;
    }

    /**
     * @param int $max
     * @return Tournament
     */
    public function setMax(int $max) : self
    {
        $this->max = $max;
        return $this;
    }

    /**
     * @return int
     */
    public function getCurrentRound() : int
    {
        return $this->currentRound;
    }

    /**
     * @param int $currentRound
     * @return Tournament
     */
    public function setCurrentRound(int $currentRound) : self
    {
        $this->currentRound = $currentRound;
        return $this;
    }

    /**
     * @return Collection<int, Player>
     */
    public function getPlayers(): Collection
    {
        return $this->players;
    }

    public function addPlayer(Player $player): self
    {
        if (!$this->players->contains($player)) {
            $this->players[] = $player;
        }

        return $this;
    }

    public function removePlayer(Player $player): self
    {
        $this->players->removeElement($player);

        return $this;
    }

    /**
     * @return Collection<int, TournamentMatch>
     */
    public function getMatches(): Collection
    {
        return $this->matches;
    }

    public function addMatch(TournamentMatch $match): self
    {
        if (!$this->matches->contains($match)) {
            $this->matches[] = $match;
            $match->setTournament($this);
        }

        return $this;
    }

    public function removeMatch(TournamentMatch $match): self
    {
        if ($this->matches->removeElement($match)) {
            // set the owning side to null (unless already changed)
            if ($match->getTournament() === $this) {
                $match->setTournament(null);
            }
        }

        return $this;
    }

    public function getMaxRound() : int
    {
        if($this->players->count() % 2 === 0) {
            return $this->players->count() - 1;
        }
        return $this->players->count();
    }

}

src/Controller/TournamentController.php
<?php

namespace App\Controller;

use App\Entity\MatchResult;
use App\Entity\Player;
use App\Entity\Tournament;
use App\Entity\TournamentMatch;
use App\Filters\TournamentFilters;
use App\Form\TournamentAddType;
use App\Form\TournamentFiltersType;
use App\Repository\PlayerScoreRepository;
use App\Repository\TournamentRepository;
use App\Service\TournamentService;
use Doctrine\ORM\EntityManagerInterface;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\IsGranted;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\HttpKernel\Exception\BadRequestHttpException;
use Symfony\Component\HttpKernel\Exception\NotFoundHttpException;
use Symfony\Component\Routing\Annotation\Route;

class TournamentController extends AbstractController
{
    /** @var TournamentRepository  */
    private $tournamentRepo;

    /** @var TournamentService */
    private $tournamentService;

    /** @var EntityManagerInterface */
    private $em;

    public function __construct(
        EntityManagerInterface $em,
        TournamentRepository $tournamentRepo,
        TournamentService $tournamentService,
    )
    {
        $this->em = $em;
        $this->tournamentRepo = $tournamentRepo;
        $this->tournamentService = $tournamentService;
    }

    #[Route('/', name: 'tournament_index')]
    public function index(Request $request): Response
    {
        $filters = new TournamentFilters();
        $form = $this->createForm(TournamentFiltersType::class, $filters);
        $form->handleRequest($request);

        $tournaments = $this->tournamentRepo->findByFilters($filters);

        return $this->render('tournament/index.html.twig', [
            'form' => $form->createView(),
            'tournaments' => $tournaments
        ]);
    }

    #[IsGranted('ROLE_ADMIN')]
    #[Route('/tournament/add', name: 'tournament_add')]
    public function add(Request $request): Response
    {
        $tournament = new Tournament();
        $form = $this->createForm(TournamentAddType::class, $tournament);
        $form->handleRequest($request);

        if($form->isSubmitted() && $form->isValid()) {
            $tournament->setCurrentRound(0);
            $this->em->persist($tournament);
            $this->em->flush();
            $this->addFlash('success', 'Nouveau tournoi crée');
            return $this->redirectToRoute('tournament_index');
        }

        return $this->render('tournament/add.html.twig', [
            'form' => $form->createView(),
        ]);
    }

    #[IsGranted('IS_AUTHENTICATED')]
    #[Route('/tournament/participate/{tournamentId}', name: 'tournament_participate')]
    public function participate(int $tournamentId)
    {
        $tournament = $this->tournamentRepo->findOneWithPlayers($tournamentId);
        if(!$tournament) {
            throw new NotFoundHttpException();
        }
        /** @var Player $player */
        $player = $this->getUser();
        if($this->tournamentService->canPlay($player, $tournament))
        {
            $tournament->addPlayer($player);
            $this->em->flush();
            $this->addFlash('success', sprintf(
                    'Vous participez au tournoi %s',
                    $tournament->getName()
                )
            );
        }
        else {
            $this->addFlash('error', sprintf(
                    'Vous ne pouvez pas participer au tournoi %s',
                    $tournament->getName()
                )
            );
        }
        return $this->redirectToRoute('tournament_index');
    }

    #[IsGranted('IS_AUTHENTICATED')]
    #[Route('/tournament/leave/{tournamentId}', name: 'tournament_leave')]
    public function leave(int $tournamentId)
    {
        $tournament = $this->tournamentRepo->findOneWithPlayers($tournamentId);
        if(!$tournament) {
            throw new NotFoundHttpException();
        }
        /** @var Player $player */
        $player = $this->getUser();
        if($this->tournamentService->canLeave($player, $tournament))
        {
            $tournament->removePlayer($player);
            $this->em->flush();
            $this->addFlash('success', sprintf(
                    'Vous ne participez plus au tournoi %s',
                    $tournament->getName()
                )
            );
        }
        else {
            $this->addFlash('error', sprintf(
                    'Vous ne pouvez pas quitter le tournoi %s',
                    $tournament->getName()
                )
            );
        }
        return $this->redirectToRoute('tournament_index');
    }

    #[Route('/tournament/details/{tournamentId}/{round}', name: 'tournament_details')]
    public function details(int $tournamentId, $round, PlayerScoreRepository $playerScoreRepository)
    {
        $tournament = $this->tournamentRepo->findWithMatches($tournamentId, $round);
        $players = $playerScoreRepository->findPlayersScore($tournamentId, $round);
        if(!$tournament || (count($players) < $round && $round != 0)) {
            //throw new NotFoundHttpException();
        }

        return $this->render('tournament/details.html.twig', [
            'tournament' => $tournament,
            'players' => $players,
            'round' => $round,
        ]);
    }

    #[IsGranted('ROLE_ADMIN')]
    #[Route('/tournament/start/{tournamentId}', name: 'tournament_start')]
    public function start(int $tournamentId): Response
    {
        $tournament = $this->tournamentRepo->findOneWithPlayers($tournamentId);
        if(!$tournament) {
            throw new NotFoundHttpException();
        }

        /** @var Player $player */
        $player = $this->getUser();

        if($this->tournamentService->canStart($player, $tournament)) {
            $tournament->setCurrentRound(1);
            $players = $tournament->players->toArray();
            $count = count($players);

            // number of players is null add a "null player"
            if($count % 2 !== 0) {
                $players[] = null;
                $count++;
            }

            for($r=1; $r<$count; $r++) {
                for($i=0;$i < $count/2; $i++) {
                    $m = new TournamentMatch();
                    $m->setWhite($players[$i]);
                    $m->setBlack($players[$count - 1 - $i]);
                    $m->setRound($r);
                    $m->setTournament($tournament);
                    $m->setResult(MatchResult::NOT_PLAYED);
                    $this->em->persist($m);

                }
                $players = array_merge(
                    [$players[0], $players[$count-1]],
                    array_slice($players, 1, $count-2)
                );
            }
            $this->em->flush();
        }
        else {
            $this->addFlash('error', 'Vous ne pouvez pas démarrer ce tournoi');
        }
        return $this->redirectToRoute('tournament_details', [
            'tournamentId' => $tournamentId,
            'round' => $tournament->getCurrentRound()
        ]);
    }

    #[IsGranted('ROLE_ADMIN')]
    #[Route('/tournament/update/{tournament}/{match}/{result}', name: 'tournament_match_update')]
    public function updateResult(Tournament $tournament, TournamentMatch $match, $result): Response
    {
        $result = MatchResult::tryFrom($result);
        if(!$result) {
            throw new NotFoundHttpException();
        }
        /** @var $player Player */
        $player = $this->getUser();
        if($this->tournamentService->canUpdate($player, $match, $tournament)) {
            $match->setResult($result);
            $this->em->flush();
            $this->addFlash('success', 'OK');
        }
        else {
            $this->addFlash('error', 'Vous ne pouvez pas mettre à jour ce match');
        }
        return $this->redirectToRoute('tournament_details', [
            'tournamentId' => $tournament->getId(),
            'round' => $tournament->getCurrentRound()
        ]);
    }

    #[IsGranted('ROLE_ADMIN')]
    #[Route('/tournament/next/{tournament}', name: 'tournament_next')]
    public function next(Tournament $tournament): Response
    {
        /** @var $player Player */
        $player = $this->getUser();
        if($this->tournamentService->canNextRound($player, $tournament)) {
            $tournament->setCurrentRound($tournament->getCurrentRound() + 1);
            $this->em->flush();
            $this->addFlash('success', 'OK');
        }
        else {
            $this->addFlash('error', 'Vous ne pouvez pas terminer cette ronde');
        }
        return $this->redirectToRoute('tournament_details', [
            'tournamentId' => $tournament->getId(),
            'round' => $tournament->getCurrentRound()
        ]);
    }
}

templates/tournament/add.html.twig
{% extends 'base.html.twig' %}

{% block title %}Nouveau tournoi{% endblock %}

{% block body %}
    <form method="post">
        {{ form_widget(form._token) }}
        <div class="row">
            <div class="col-md-6 mb-2">
                {{ form_row(form.name) }}
            </div>
            <div class="col-md-6 mb-2 d-flex align-items-end">
                <div class="form-switch">
                    {{ form_widget(form.ranked) }}
                    {{ form_label(form.ranked) }}
                </div>
            </div>
        </div>
        <div class="row">
            <div class="col-md-6 mb-2">
                {{ form_row(form.date) }}
            </div>
            <div class="col-md-6 mb-2">
                {{ form_row(form.location) }}
            </div>
        </div>
        <div class="row">
            <div class="col-md-6 mb-2">
                <div>
                    {{ form_label(form.eloMin) }} : <span class="range-value">{{ form.eloMin.vars.data }}</span>
                    {{ form_widget(form.eloMin) }}
                    {{ form_errors(form.eloMin) }}
                </div>
            </div>
            <div class="col-md-6 mb-2">
                <div>
                    {{ form_label(form.eloMax) }} : <span class="range-value">{{ form.eloMax.vars.data }}</span>
                    {{ form_widget(form.eloMax) }}
                    {{ form_errors(form.eloMax) }}
                </div>
            </div>
        </div>
        <div class="row">
            <div class="col-md-6 mb-2">
                <div>
                    {{ form_label(form.min) }} : <span class="range-value">{{ form.min.vars.data }}</span>
                    {{ form_widget(form.min) }}
                    {{ form_errors(form.min) }}
                </div>
            </div>
            <div class="col-md-6 mb-2">
                <div>
                    {{ form_label(form.max) }} : <span class="range-value">{{ form.max.vars.data }}</span>
                    {{ form_widget(form.max) }}
                    {{ form_errors(form.max) }}
                </div>
            </div>
        </div>
        <div class="row">
            <div class="col-md-6 mb-2">
                {{ form_row(form.categories) }}
            </div>
            <div class="col-md-6 mb-2">
                {{ form_row(form.genders) }}
            </div>
        </div>
        <div class="row">
            <div class="col-md-12">
                <div class="d-flex justify-content-end">
                    <button class="btn btn-primary">Sauvegarder</button>
                </div>
            </div>
        </div>
    </form>
{% endblock %}

templates/tournament/details.html.twig
{% extends 'base.html.twig' %}

{% block body %}
    <h4>
        {{ tournament.name }}
    </h4>
    <div class="row">
        <div class="col-md-4">
            <h5>Classement</h5>
            <table class="table">
                <thead>
                    <tr>
                        <th>Joueur</th>
                        <th>V</th>
                        <th>N</th>
                        <th>D</th>
                        <th>Score</th>
                    </tr>
                </thead>
                <tbody>
                {% for player in players %}
                    <tr>
                        <td><div class="img-thumbnail">{{ player.image | playerImg }}</div> {{ player.firstName }} {{ player.lastName }}</td>
                        <td>{{ player.victories }}</td>
                        <td>{{ player.ties }}</td>
                        <td>{{ player.defeats }}</td>
                        <td>{{ player.score }}</td>
                    </tr>
                {% endfor %}
                </tbody>
            </table>
        </div>
        <div class="col-md-8">
            {% if tournament.currentRound > 0 %}
                <h5>
                    Ronde: {{ round }}
                </h5>
                <div class="d-flex justify-content-between">
                    <div>
                        {% if round > 1 %}
                            <a href="{{ path('tournament_details', { 'tournamentId' : tournament.id, 'round' : round - 1 }) }}" class="btn btn-info text-white">Ronde précédente</a>
                        {% endif %}
                    </div>
                    <div>
                        {% if round < tournament.currentRound and tournament.maxRound > round %}
                            <a href="{{ path('tournament_details', { 'tournamentId' : tournament.id, 'round' : round + 1 }) }}" class="btn btn-info text-white">Ronde suivante</a>
                        {% endif %}
                        {% if(canNextRound(app.user, tournament)) %}
                            <a href="{{ path('tournament_next', { 'tournament': tournament.id }) }}" class="btn btn-danger">Terminer la ronde</a>
                        {% endif %}
                    </div>
                </div>
                <ul class="mt-5 list-group">
                {% for match in tournament.matches %}
                    <li class="list-group-item">
                        <div class="row">
                            <div class="col-8 match">
                                {{ match.white | playerName }}
                                <span>VS</span>
                                {{ match.black | playerName }}
                            </div>
                            <div class="col-4">
                                {% if canUpdate(app.user, match, tournament) %}
                                    <select data-match="{{ match.id }}" data-tournament="{{ tournament.id }}" class="form-select resultSelect">
                                        {{ optionsEnum('App\\Entity\\MatchResult', match.result, ['BYE']) }}
                                    </select>
                                {% else %}
                                    <select class="form-select disabled" disabled>
                                        <option>{{ match.result.value }}</option>
                                    </select>
                                {% endif %}
                            </div>
                        </div>
                    </li>
                {% endfor %}
                </ul>
            {% endif %}
        </div>
    </div>
    <div class="row">
        <div class="col-md-12 mt-2 d-flex justify-content-end">

            {% if canStart(app.user, tournament) %}
                <a href="{{ path('tournament_start', { 'tournamentId' : tournament.id }) }}" class="btn btn-danger">Démarrer</a>
            {% endif %}
        </div>
    </div>
{% endblock %}

{% block title %}
    Details du tournoi {{ tournament.name }}
{% endblock %}

{% block javascripts %}
    <script>
        const resultSelects = document.getElementsByClassName('resultSelect');
        for(let resultSelect of resultSelects) {
            resultSelect.addEventListener('change', e => {
                const result = e.target.value;
                const { match, tournament } = e.target.dataset;
                window.location.href = '/tournament/update/' + tournament + '/' + match + '/' + result;
            });
        }
    </script>
{% endblock %}

templates/tournament/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Tournois{% endblock %}

{% block body %}
    <div class="card">
        <div class="card-header d-flex justify-content-between" data-bs-toggle="collapse" data-bs-target="#filters">
            <h4>Filtres</h4>
            <button class="btn btn-light"><i class="fa fa-cog"></i></button>
        </div>
        <div class="card-body collapse" id="filters">
            <form method="get">
                <div class="row">
                    <div class="mb-2 col-md-6">
                        {{ form_row(form.name) }}
                    </div>
                </div>
                <div class="row">
                    <div class="mb-2 col-md-6">
                        <div class="form-switch">
                            {{ form_widget(form.closed) }}
                            {{ form_label(form.closed) }}
                        </div>
                    </div>
                </div>
                <div class="row">
                    <div class="mb-2 col-12 d-flex justify-content-end">
                        <div>
                            <button class="btn btn-primary">Rechercher <i class="fa fa-search"></i></button>
                        </div>
                    </div>
                </div>
            </form>
        </div>
    </div>
    <div class="card card-body mt-2">
        {% if tournaments | length %}
            <table class="table">
                <thead>
                <tr>
                    <th>Nom</th>
                    <th>Date</th>
                    <th>Categories</th>
                    <th>Genres</th>
                    <th>Classé</th>
                    <th>ELO min</th>
                    <th>ELO max</th>
                    <th>Players</th>
                    <th>Actions</th>
                </tr>
                </thead>
                <tbody>
                {% for tournament in tournaments %}
                    <tr>
                        <td>{{ tournament.name }}</td>
                        <td>{{ tournament.date | date('d/m/Y') }}</td>
                        <td>{{ tournament.categories | implodeEnum(' ') }}</td>
                        <td>{{ tournament.genders | implodeEnum(' ') }}</td>
                        <td>{{ tournament.ranked ? 'Classé' : 'Non Classé' }}</td>
                        <td>{{ tournament.eloMin }}</td>
                        <td>{{ tournament.eloMax }}</td>
                        <td>
                            <span class="{{ tournament.players | length < tournament.min ? 'text-danger' : 'text-success' }}">{{ tournament.players | length }}</span>/{{ tournament.max }} (min: {{ tournament.min }})
                        </td>
                        <td>
                            <a href="{{ path('tournament_details', { 'tournamentId': tournament.id, 'round' : tournament.currentRound }) }}" class="btn btn-info btn-sm text-white icon">
                                <i class="fa fa-search"></i>
                            </a>
                            {% if canPlay(app.user, tournament) %}
                                <a href="{{ path('tournament_participate', { 'tournamentId': tournament.id }) }}" class="btn btn-success btn-sm icon">
                                    <i class="fa fa-add"></i>
                                </a>
                            {% endif %}
                            {% if canLeave(app.user, tournament) %}
                                <a href="{{ path('tournament_leave', { 'tournamentId': tournament.id }) }}" class="btn btn-danger btn-sm icon">
                                    <i class="fa fa-remove"></i>
                                </a>
                            {% endif %}
                        </td>
                    </tr>
                {% endfor %}
                </tbody>
            </table>
        {% else %}
            <p>Aucun tournoi</p>
        {% endif %}
    </div>
{% endblock %}